import assert from "node:assert/strict";
import test from "node:test";
import { validateStationAreaDetails } from "../lib/client/station-area-details.ts";
import { validateMeetingResponse } from "../lib/client/meeting-response.ts";
import type { MeetingRequest, MeetingResponse, MeetingStationArea } from "../lib/client/meeting-response.ts";

const request = { contractVersion: "meeet-meeting/v3", participants: [{ id: "participant-1", mode: "transit", origin: { label: "A", latitude: 48.137, longitude: 11.576 } }, { id: "participant-2", mode: "transit", origin: { label: "B", latitude: 48.126, longitude: 11.605 } }], tolerancePercent: 10, searchStartAt: "2026-08-11T08:05:00.000Z", changeTimePreset: "medium" } as MeetingRequest;
const area = { stationAreaId: "area-1", name: "Central", coordinate: { latitude: 48.137, longitude: 11.576 }, mode: "sbahn", classification: "fair", redArrivalSeconds: 600, blueArrivalSeconds: 660, fasterParticipant: "red", withinSelectedTolerance: true } as const;
const schedule = { contractVersion: "meeet-scheduled-routing/v1" as const, feedId: "fixture", timeZone: "Europe/Berlin", scheduleContentHash: "a".repeat(64), compiledArtifactId: "b".repeat(64), serviceDateRange: { firstDate: "2026-08-01", lastDate: "2026-08-31" }, acquisition: { sourceUrl: "https://example.test/feed.zip", retrievedAt: "2026-08-01T00:00:00.000Z", rawArchiveByteSize: 1, rawArchiveSha256: "c".repeat(64), feedVersion: "fixture", feedValidFrom: "2026-08-01", feedValidUntil: "2026-08-31", attribution: "Fixture", officialAttribution: "MVV", officialLicense: { name: "CC", url: "https://example.test/license" }, officialProvenance: { source: "feed" as const, policyId: null } } };
const accessProvider = { name: "fixture", deployment: "fixture" as const, dataKind: "demo-static" as const, liveData: false as const, asOf: "fixture", notes: "Fixture", provenance: { role: "access" as const, provider: "fixture", deployment: "fixture" as const, dataKind: "demo-static" as const, liveData: false as const, sourceUrl: null, license: null, attribution: "Fixture", version: "fixture", retrievedAt: "fixture", notes: "Fixture", feeds: null } };
const baseResult: MeetingResponse = { contractVersion: "meeet-meeting/v3", status: "ok", reason: null, participants: [{ id: "participant-1", color: "red", mode: "transit", origin: request.participants[0].origin, accessSeeds: [] }, { id: "participant-2", color: "blue", mode: "transit", origin: request.participants[1].origin, accessSeeds: [] }], stationAreas: [area], metadata: { schedule, surface: { contractVersion: "meeet-scheduled-routing/v1", scheduleContentHash: schedule.scheduleContentHash, compiledArtifactId: schedule.compiledArtifactId, feedId: schedule.feedId, timeZone: schedule.timeZone, searchStartAt: request.searchStartAt, routingHorizonSeconds: 86400, selectedTolerancePercent: 10, walkingVelocityMetersPerSecond: 1.4, walkingSecondsRoundingRule: "ceil(distanceMetres / velocityMetresPerSecond), with zero distance taking zero seconds", transferRadiusMeters: 100, accessSeedCounts: [0, 0], stationAreaCount: 1, connectionCount: 1, changeTimeSeconds: 300, coverage: "scheduled-service-day-local-radius/v1", representativePointBasis: "station-area-coordinate/v1", classificationMethod: "scheduled-arrival-comparison-with-selected-tolerance/v1", classificationBasis: "scheduled-station-area-arrival/v1", finalWalkingMethod: "scheduled-access-and-transfer-walking/v1" }, accessProvider, stationAreas: { count: 1, coverage: "official-munich-boundary-with-connected-artifact-station-areas/v1", selection: "all-eligible-scheduled-station-areas/v1" }, coverage: "munich-scheduled-station-area-meeting/v1" } };
function details() { return { contractVersion: "meeet-station-area-details/v1", status: "ok", reason: null, stationArea: area, participants: request.participants.map((participant, index) => { const seconds = index === 0 ? 600 : 660; const arrival = new Date(Date.parse(request.searchStartAt) + seconds * 1000).toISOString(); return { id: participant.id, color: index === 0 ? "red" : "blue", origin: { ...participant.origin }, status: "available", unavailableReason: null, terminal: { totalSeconds: seconds, arrivalAt: arrival } }; }) as unknown as [Record<string, unknown>, Record<string, unknown>], basis: { contractVersion: "meeet-meeting/v3", searchStartAt: request.searchStartAt, selectedTolerancePercent: 10, routingHorizonSeconds: 86400, walkingVelocityMetersPerSecond: 1.4, walkingSecondsRoundingRule: "ceil(distanceMetres / velocityMetresPerSecond), with zero distance taking zero seconds", transferRadiusMeters: 100, changeTimeSeconds: 300, deterministicSelectionPolicy: "earliest-arrival/canonical-scan-first/v1", schedule: structuredClone(baseResult.metadata.schedule), accessProvider: structuredClone(baseResult.metadata.accessProvider) } }; }
test("accepts the strict production detail shape", () => { const result = validateStationAreaDetails(details(), baseResult, request, "calc-1", "area-1"); assert.equal(result.success, true, result.success ? "" : result.message); });
test("fixture is independently a validated v3 meeting response", () => { const result = validateMeetingResponse(baseResult, request); assert.equal(result.success, true, result.success ? "" : JSON.stringify(result.issues)); });
test("rejects unknown fields, marker tampering, wrong origins, totals, and arrival retiming", () => { const unknown = { ...details(), unexpected: true }; assert.equal(validateStationAreaDetails(unknown, baseResult, request, "calc-1", "area-1").success, false, "unknown"); const marker = details(); (marker as unknown as { stationArea: unknown }).stationArea = { ...area, classification: "red" }; assert.equal(validateStationAreaDetails(marker, baseResult, request, "calc-1", "area-1").success, false, "marker"); const origin = details(); (origin.participants[0] as Record<string, unknown>).origin = { label: "Tampered", latitude: 48.137, longitude: 11.576 }; assert.equal(validateStationAreaDetails(origin, baseResult, request, "calc-1", "area-1").success, false, "origin"); const total = details(); (total.participants[0]!.terminal as Record<string, unknown>).totalSeconds = 601; assert.equal(validateStationAreaDetails(total, baseResult, request, "calc-1", "area-1").success, false, "total"); const arrival = details(); (arrival.participants[0]!.terminal as Record<string, unknown>).arrivalAt = "2026-08-11T08:16:00.000Z"; assert.equal(validateStationAreaDetails(arrival, baseResult, request, "calc-1", "area-1").success, false, "arrival"); });
test("rejects status, reason, and provenance retiming tampering", () => { const status = details(); (status as Record<string, unknown>).status = "no-result"; (status as Record<string, unknown>).reason = "no-access-seeds"; assert.equal(validateStationAreaDetails(status, baseResult, request, "calc-1", "area-1").success, false, "status"); const reason = details(); (reason as Record<string, unknown>).reason = "no-reachable-stations"; assert.equal(validateStationAreaDetails(reason, baseResult, request, "calc-1", "area-1").success, false, "reason"); const provenance = details(); ((provenance.basis.schedule.acquisition as unknown) as Record<string, unknown>).feedVersion = "tampered"; assert.equal(validateStationAreaDetails(provenance, baseResult, request, "calc-1", "area-1").success, false, "provenance"); const retimed = details(); (retimed.participants[0]!.terminal as Record<string, unknown>).arrivalAt = "2026-08-11T08:16:00.000Z"; assert.equal(validateStationAreaDetails(retimed, baseResult, request, "calc-1", "area-1").success, false, "retimed"); });
test("rejects unavailable participants that invent terminal evidence", () => { const payload = details(); payload.participants[0] = { id: "participant-1", color: "red", origin: request.participants[0].origin, status: "unavailable", unavailableReason: "station-area-unclassified", terminal: { totalSeconds: null, arrivalAt: null } }; assert.equal(validateStationAreaDetails(payload, baseResult, request, "calc-1", "area-1").success, false); });
test("binds the basis change time to the submitted preset", () => { const payload = details(); (payload.basis as Record<string, unknown>).changeTimeSeconds = 600; assert.equal(validateStationAreaDetails(payload, baseResult, request, "calc-1", "area-1").success, false); const missing = details(); delete (missing.basis as Record<string, unknown>).changeTimeSeconds; assert.equal(validateStationAreaDetails(missing, baseResult, request, "calc-1", "area-1").success, false); });
test("binds terminal totals and arrivals to the meeting-surface marker", () => { const payload = details(); (payload.participants[1]!.terminal as Record<string, unknown>).totalSeconds = 600; assert.equal(validateStationAreaDetails(payload, baseResult, request, "calc-1", "area-1").success, false); const unavailable = details(); (unavailable.participants[0] as Record<string, unknown>).status = "unavailable"; (unavailable.participants[0] as Record<string, unknown>).unavailableReason = "station-area-unavailable-for-participant"; (unavailable.participants[0]!.terminal as Record<string, unknown>).totalSeconds = null; (unavailable.participants[0]!.terminal as Record<string, unknown>).arrivalAt = null; assert.equal(validateStationAreaDetails(unavailable, baseResult, request, "calc-1", "area-1").success, false); });
import { sortStationAreasByWorstTime } from "../components/MeetPlanner.tsx";

test("sorts station areas by worst of both times ascending with deterministic tie breaks", () => {
  const s1: MeetingStationArea = { stationAreaId: "s1", name: "Station 1 (20m vs 30m)", coordinate: { latitude: 48.1, longitude: 11.5 }, mode: "sbahn", classification: "fair", redArrivalSeconds: 1200, blueArrivalSeconds: 1800, fasterParticipant: "red", withinSelectedTolerance: true };
  const s2: MeetingStationArea = { stationAreaId: "s2", name: "Station 2 (25m vs 25m)", coordinate: { latitude: 48.1, longitude: 11.5 }, mode: "ubahn", classification: "fair", redArrivalSeconds: 1500, blueArrivalSeconds: 1500, fasterParticipant: null, withinSelectedTolerance: true };
  const s3: MeetingStationArea = { stationAreaId: "s3", name: "Station 3 (10m vs 40m)", coordinate: { latitude: 48.1, longitude: 11.5 }, mode: "tram", classification: "red", redArrivalSeconds: 600, blueArrivalSeconds: 2400, fasterParticipant: "red", withinSelectedTolerance: false };
  const sSingle: MeetingStationArea = { stationAreaId: "s-single", name: "Single Reachable", coordinate: { latitude: 48.1, longitude: 11.5 }, mode: "bus", classification: "red", redArrivalSeconds: 900, blueArrivalSeconds: null, fasterParticipant: "red", withinSelectedTolerance: false };
  const sUnclassified: MeetingStationArea = { stationAreaId: "s-unclassified", name: "Unclassified", coordinate: { latitude: 48.1, longitude: 11.5 }, mode: "bus", classification: "unclassified", redArrivalSeconds: null, blueArrivalSeconds: null, fasterParticipant: null, withinSelectedTolerance: false };

  // s2 worst is 1500 (25m)
  // s1 worst is 1800 (30m)
  // s3 worst is 2400 (40m)
  // sSingle is single reachable (after two-reachable)
  // sUnclassified is unclassified (last)
  const sorted = sortStationAreasByWorstTime([s3, sUnclassified, s1, sSingle, s2]);
  assert.deepEqual(sorted.map((s) => s.stationAreaId), ["s2", "s1", "s3", "s-single", "s-unclassified"]);
});