"use client";
import { useEffect, useRef, useState, type MutableRefObject } from "react";
import { AttributionControl, Map, Marker, NavigationControl, setWorkerUrl, type GeoJSONSource } from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import type { MeetingCell, MeetingStationArea } from "@/lib/client/meeting-response";
export type MapParticipant = { id: string; number: number; label: string; latitude: number; longitude: number; color: "#e85d4a" | "#3d70c9" };
export type ParticipantMapCoordinate = { latitude: number; longitude: number };
type Props = { participants: readonly MapParticipant[]; cells: readonly MeetingCell[]; stationAreas: readonly MeetingStationArea[]; onParticipantMove: (id: string, coordinate: ParticipantMapCoordinate) => void; resultState: "initial" | "ok" | "no-result"; originDraggingEnabled: boolean };
type Collection = { type: "FeatureCollection"; features: Array<{ type: "Feature"; id: string; properties: Record<string, string>; geometry: MeetingCell["geometry"] | { type: "Point"; coordinates: [number, number] } }> };
const MUNICH_CENTER: [number, number] = [11.576, 48.137];
const DEFAULT_MAP_STYLE_URL = "https://tiles.openfreemap.org/styles/liberty";
setWorkerUrl("/vendor/maplibre-gl/maplibre-gl-worker.mjs");
const cellsData = (cells: readonly MeetingCell[]): Collection => ({ type: "FeatureCollection", features: cells.filter((cell) => cell.classification !== "unclassified").map((cell) => ({ type: "Feature", id: cell.id, properties: { classification: cell.classification }, geometry: cell.geometry })) });
const stationData = (areas: readonly MeetingStationArea[]): Collection => ({ type: "FeatureCollection", features: areas.map((area) => ({ type: "Feature", id: area.stationAreaId, properties: { classification: area.classification }, geometry: { type: "Point", coordinates: [area.coordinate.longitude, area.coordinate.latitude] } })) });
function syncOrigins(map: Map, participants: readonly MapParticipant[], markers: MutableRefObject<globalThis.Map<string, Marker>>, inputs: MutableRefObject<Pick<Props, "onParticipantMove" | "originDraggingEnabled">>) { const ids = new Set(participants.map((p) => p.id)); markers.current.forEach((marker, id) => { if (!ids.has(id)) { marker.remove(); markers.current.delete(id); } }); participants.forEach((p) => { let marker = markers.current.get(p.id); if (!marker) { const element = document.createElement("button"); element.type = "button"; element.className = "meeet-origin-marker"; element.textContent = String(p.number); element.style.backgroundColor = p.color; element.setAttribute("aria-label", `${p.label} origin. Drag to adjust.`); marker = new Marker({ element, draggable: inputs.current.originDraggingEnabled }).setLngLat([p.longitude, p.latitude]).addTo(map); marker.on("dragend", () => { if (!inputs.current.originDraggingEnabled) return; const point = marker!.getLngLat(); inputs.current.onParticipantMove(p.id, { latitude: point.lat, longitude: point.lng }); }); markers.current.set(p.id, marker); } else { marker.setLngLat([p.longitude, p.latitude]); marker.setDraggable(inputs.current.originDraggingEnabled); } }); }
export default function MapLibreCanvas({ participants, cells, stationAreas, onParticipantMove, resultState, originDraggingEnabled }: Props) {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<Map | null>(null); const markersRef = useRef(new globalThis.Map<string, Marker>()); const inputs = useRef({ participants, onParticipantMove, originDraggingEnabled }); const [state, setState] = useState<"loading" | "ready" | "unavailable">("loading"); const styleUrl = process.env.NEXT_PUBLIC_MAP_STYLE_URL || DEFAULT_MAP_STYLE_URL; const attribution = process.env.NEXT_PUBLIC_MAP_ATTRIBUTION;
  useEffect(() => { inputs.current = { participants, onParticipantMove, originDraggingEnabled }; }, [participants, onParticipantMove, originDraggingEnabled]);
  useEffect(() => { if (!containerRef.current) { setState("unavailable"); return; } let active = true; let map: Map | null = null; let hasCartography = false; let resizeObserver: ResizeObserver | null = null; try { map = new Map({ container: containerRef.current, style: styleUrl, center: MUNICH_CENTER, zoom: 11, attributionControl: false }); mapRef.current = map; resizeObserver = new ResizeObserver(() => map?.resize()); resizeObserver.observe(containerRef.current); map.addControl(new AttributionControl({ compact: true, customAttribution: attribution }), "bottom-right"); map.addControl(new NavigationControl({ showCompass: false }), "top-right"); map.once("style.load", () => { if (!map || !active) return; hasCartography = map.getStyle().layers?.some((layer) => layer.type !== "background") ?? false; if (!hasCartography) { setState("unavailable"); return; } map.addSource("meeet-surface", { type: "geojson", data: cellsData([]) }); (["red", "blue", "fair"] as const).forEach((classification) => map!.addLayer({ id: `meeet-surface-${classification}`, type: "fill", source: "meeet-surface", filter: ["==", ["get", "classification"], classification], paint: { "fill-color": classification === "red" ? "#e85d4a" : classification === "blue" ? "#3d70c9" : "#f0ca43", "fill-opacity": .55 } })); map.addSource("meeet-station-areas", { type: "geojson", data: stationData([]) }); (["red", "blue", "fair", "unclassified"] as const).forEach((classification) => map!.addLayer({ id: `meeet-stations-${classification}`, type: "circle", source: "meeet-station-areas", filter: ["==", ["get", "classification"], classification], paint: { "circle-color": classification === "red" ? "#e85d4a" : classification === "blue" ? "#3d70c9" : classification === "fair" ? "#f0ca43" : "#65716a", "circle-radius": classification === "unclassified" ? 6 : 7, "circle-stroke-color": "#fffdf8", "circle-stroke-width": 2 } })); syncOrigins(map, inputs.current.participants, markersRef, inputs); }); map.once("idle", () => { if (active) { map?.resize(); setState(!hasCartography ? "unavailable" : "ready"); } }); map.on("error", () => { if (active) setState("unavailable"); }); } catch { queueMicrotask(() => { if (active) setState("unavailable"); }); } return () => { active = false; resizeObserver?.disconnect(); markersRef.current.forEach((marker) => marker.remove()); markersRef.current.clear(); map?.remove(); mapRef.current = null; }; }, [styleUrl, attribution]);
  useEffect(() => { const map = mapRef.current; if (!map || state !== "ready") return; (map.getSource("meeet-surface") as GeoJSONSource | undefined)?.setData(cellsData(cells)); (map.getSource("meeet-station-areas") as GeoJSONSource | undefined)?.setData(stationData(stationAreas)); syncOrigins(map, participants, markersRef, inputs); }, [cells, stationAreas, participants, onParticipantMove, originDraggingEnabled, state]);
  const label = resultState === "ok" ? `Munich meeting surface with ${stationAreas.length} calculated station-area markers` : resultState === "no-result" ? `Munich meeting map with ${stationAreas.length} unclassified station-area markers` : "Munich meeting map with two participant origins";
  return <section className="map-frame" aria-label={label} data-map-state={state} data-map-style="configured" data-station-area-count={stationAreas.length}><h2 className="sr-only">Munich meeting map</h2><div ref={containerRef} className="absolute inset-0" style={{ width: "100%", height: "100%" }} />{state === "loading" && <div className="map-message" role="status">Loading Munich map…</div>}{state === "unavailable" && <div className="map-message" role="status"><strong>Map unavailable</strong><span>The meeting result is still available as a surface summary.</span></div>}</section>;
}
