"use client";

import { useEffect, useMemo, useRef, useState, type MutableRefObject } from "react";
import { AttributionControl, Map, Marker, NavigationControl, setWorkerUrl, type GeoJSONSource } from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import type { MeetingStationArea } from "@/lib/client/meeting-response";
import { buildStationTerritories, type StationTerritory } from "@/lib/client/station-territories";

export type MapParticipant = { id: string; number: number; label: string; latitude: number; longitude: number; color: "#e85d4a" | "#3d70c9" };
export type ParticipantMapCoordinate = { latitude: number; longitude: number };
type Props = { participants: readonly MapParticipant[]; stationAreas: readonly MeetingStationArea[]; onParticipantMove: (id: string, coordinate: ParticipantMapCoordinate) => void; resultState: "initial" | "ok" | "no-result"; originDraggingEnabled: boolean };
type Geometry = { type: "MultiPolygon"; coordinates: number[][][][] } | { type: "Point"; coordinates: [number, number] };
type FeatureCollection = { type: "FeatureCollection"; features: Array<{ type: "Feature"; id: string; properties: Record<string, string>; geometry: Geometry }> };
const MUNICH_CENTER: [number, number] = [11.576, 48.137];
const DEFAULT_MAP_STYLE_URL = "https://tiles.openfreemap.org/styles/liberty";
setWorkerUrl("/vendor/maplibre-gl/maplibre-gl-worker.mjs");

function territoryData(areas: readonly MeetingStationArea[]): FeatureCollection {
  // Build from every station area, then omit only unclassified fills. Markers below
  // deliberately retain the complete station-area set, including neutral stations.
  if (areas.length === 0 || areas.every((area) => area.classification === "unclassified")) return { type: "FeatureCollection", features: [] };
  return { type: "FeatureCollection", features: (buildStationTerritories(areas) as readonly StationTerritory[]).filter((territory) => territory.classification !== "unclassified").map((territory) => ({ type: "Feature", id: territory.stationAreaId, properties: { classification: territory.classification }, geometry: territory.geometry as unknown as Geometry })) };
}
function stationData(areas: readonly MeetingStationArea[]): FeatureCollection { return { type: "FeatureCollection", features: areas.map((area) => ({ type: "Feature", id: area.stationAreaId, properties: { classification: area.classification }, geometry: { type: "Point", coordinates: [area.coordinate.longitude, area.coordinate.latitude] } })) }; }
function syncOrigins(map: Map, participants: readonly MapParticipant[], markers: MutableRefObject<globalThis.Map<string, Marker>>, inputs: MutableRefObject<Pick<Props, "onParticipantMove" | "originDraggingEnabled">>) { const ids = new Set(participants.map((p) => p.id)); markers.current.forEach((marker, id) => { if (!ids.has(id)) { marker.remove(); markers.current.delete(id); } }); participants.forEach((p) => { let marker = markers.current.get(p.id); if (!marker) { const element = document.createElement("button"); element.type = "button"; element.className = "meeet-origin-marker"; element.textContent = String(p.number); element.style.backgroundColor = p.color; element.setAttribute("aria-label", `${p.label} origin. Drag to adjust.`); marker = new Marker({ element, draggable: inputs.current.originDraggingEnabled }).setLngLat([p.longitude, p.latitude]).addTo(map); marker.on("dragend", () => { if (!inputs.current.originDraggingEnabled) return; const point = marker!.getLngLat(); inputs.current.onParticipantMove(p.id, { latitude: point.lat, longitude: point.lng }); }); markers.current.set(p.id, marker); } else { marker.setLngLat([p.longitude, p.latitude]); marker.setDraggable(inputs.current.originDraggingEnabled); } }); }

export default function MapLibreCanvas({ participants, stationAreas, onParticipantMove, resultState, originDraggingEnabled }: Props) {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<Map | null>(null); const markersRef = useRef(new globalThis.Map<string, Marker>()); const inputs = useRef({ participants, onParticipantMove, originDraggingEnabled }); const [state, setState] = useState<"loading" | "ready" | "unavailable">("loading"); const styleUrl = process.env.NEXT_PUBLIC_MAP_STYLE_URL || DEFAULT_MAP_STYLE_URL; const attribution = process.env.NEXT_PUBLIC_MAP_ATTRIBUTION;
  const stations = useMemo(() => stationData(stationAreas), [stationAreas]);
  const [territoryFeatureCount, setTerritoryFeatureCount] = useState(0);
  useEffect(() => { inputs.current = { participants, onParticipantMove, originDraggingEnabled }; }, [participants, onParticipantMove, originDraggingEnabled]);
  useEffect(() => { if (!containerRef.current) { setState("unavailable"); return; } let active = true; let map: Map | null = null; let resizeObserver: ResizeObserver | null = null; let mapFailed = false; const fail = () => { mapFailed = true; if (active) setState("unavailable"); }; try { map = new Map({ container: containerRef.current, style: styleUrl, center: MUNICH_CENTER, zoom: 11, attributionControl: false }); mapRef.current = map; resizeObserver = new ResizeObserver(() => map?.resize()); resizeObserver.observe(containerRef.current); map.addControl(new AttributionControl({ compact: true, customAttribution: attribution }), "bottom-right"); map.addControl(new NavigationControl({ showCompass: false }), "top-right"); map.on("error", fail); map.once("style.load", () => { if (!map || !active || mapFailed) return; const hasCartography = map.getStyle().layers?.some((layer) => layer.type !== "background") ?? false; if (!hasCartography) { fail(); return; } map.addSource("meeet-territories", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); (["red", "blue", "fair"] as const).forEach((classification) => map!.addLayer({ id: `meeet-territory-${classification}`, type: "fill", source: "meeet-territories", filter: ["==", ["get", "classification"], classification], paint: { "fill-color": classification === "red" ? "#e85d4a" : classification === "blue" ? "#3d70c9" : "#f0ca43", "fill-opacity": 1 } })); map.addSource("meeet-station-areas", { type: "geojson", data: stationData([]) }); (["red", "blue", "fair", "unclassified"] as const).forEach((classification) => map!.addLayer({ id: `meeet-stations-${classification}`, type: "circle", source: "meeet-station-areas", filter: ["==", ["get", "classification"], classification], paint: { "circle-color": classification === "red" ? "#e85d4a" : classification === "blue" ? "#3d70c9" : classification === "fair" ? "#f0ca43" : "#65716a", "circle-radius": classification === "unclassified" ? 6 : 7, "circle-stroke-color": "#fffdf8", "circle-stroke-width": 2 } })); syncOrigins(map, inputs.current.participants, markersRef, inputs); map.once("idle", () => { if (active && !mapFailed) setState("ready"); }); }); } catch { fail(); } return () => { active = false; resizeObserver?.disconnect(); markersRef.current.forEach((marker) => marker.remove()); markersRef.current.clear(); map?.remove(); mapRef.current = null; }; }, [styleUrl, attribution]);
  useEffect(() => { const map = mapRef.current; if (!map || state !== "ready") return; const territorySource = map.getSource("meeet-territories") as GeoJSONSource | undefined; const stationSource = map.getSource("meeet-station-areas") as GeoJSONSource | undefined; territorySource?.setData({ type: "FeatureCollection", features: [] }); setTerritoryFeatureCount(0); stationSource?.setData(stations); const generated = territoryData(stationAreas); territorySource?.setData(generated); setTerritoryFeatureCount(generated.features.length); syncOrigins(map, participants, markersRef, inputs); }, [stationAreas, stations, participants, onParticipantMove, originDraggingEnabled, state]);
  const label = resultState === "ok" ? `Munich meeting territory map with ${stationAreas.length} calculated station-area markers; unclassified territories are unfilled and gray dots are unclassified station areas` : resultState === "no-result" ? `Munich meeting territory map with ${stationAreas.length} unclassified station-area markers; unclassified territories are unfilled and gray dots are unclassified station areas` : "Munich meeting map with two participant origins; unclassified territories are unfilled and gray dots are unclassified station areas";
  return <section className="map-frame" aria-label={label} data-map-state={state} data-map-style="configured" data-station-area-count={stationAreas.length} data-station-marker-count={stationAreas.length} data-territory-source="shared" data-territory-fill-layers="3" data-territory-feature-count={territoryFeatureCount}><h2 className="sr-only">Munich meeting map</h2><div ref={containerRef} className="absolute inset-0" style={{ width: "100%", height: "100%" }} />{state === "loading" && <div className="map-message" role="status">Loading Munich map…</div>}{state === "unavailable" && <div className="map-message" role="status"><strong>Map unavailable</strong><span>The station-area territory map is unavailable; unclassified territories are unfilled. The planned route calculation is still separate.</span></div>}</section>;
}
